module.exports.categories = [
  {
    title: "Salary",
    icon: "MoneyBag",
    iconColor: "#00ff00",
    backgroundColor: "#756AB6",
    expenseType: "income",
  },
  {
    title: "Groceries",
    icon: "Cart",
    iconColor: "#ff0000",
    backgroundColor: "#E36414",
    expenseType: "spend",
  },
  {
    title: "Rent",
    icon: "Home",
    iconColor: "#0000ff",
    backgroundColor: "#EAD196",
    expenseType: "spend",
  },
  {
    title: "Utilities",
    icon: "Wifi",
    iconColor: "#ffff00",
    backgroundColor: "#AC87C5",
    expenseType: "spend",
  },
  {
    title: "Dining Out",
    icon: "Cup",
    iconColor: "#ff9900",
    backgroundColor: "#DE8F5F",
    expenseType: "spend",
  },
  {
    title: "Entertainment",
    icon: "Headphones",
    iconColor: "#9900cc",
    backgroundColor: "#527853",
    expenseType: "spend",
  },
  {
    title: "Healthcare",
    icon: "Hammer",
    iconColor: "#33cc33",
    backgroundColor: "#E6A4B4",
    expenseType: "spend",
  },
  {
    title: "Travel",
    icon: "Car",
    iconColor: "#3366ff",
    backgroundColor: "#7071E8",
    expenseType: "spend",
  },
];
