name: Coin Crafter CI/CD

on:
  push:
    branches:
      - master
      - frontend/**
  pull_request:
    branches:
      - master
      - frontend/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Install dependencies
      - name: Install Dependencies
        run: npm ci
        working-directory: frontend

      # Run tests
      - name: Run Tests
        run: npm test
        working-directory: frontend

      # Build frontend
      - name: Build Application
        run: npm run build
        working-directory: frontend

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      # Deploy to Amplify Hosting (Headless)
      - name: Deploy to AWS Amplify
        run: |
          cd frontend
          npm install -g @aws-amplify/cli
          amplify pull --appId d12v71fvv6s7j9 --y
          echo "🚀 Publishing app to Amplify..."
          amplify publish --yes
