name: Deploy Frontend via Amplify (Headless CI)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies & build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to Amplify (Headless)
        run: |
          cd frontend
          npm install -g @aws-amplify/cli

          AMPLIFY='{
            "projectName":"CoinCrafter",
            "appId":"d2moczoskrm9xc",
            "envName":"dev",
            "defaultEditor":"none"
          }'

          FRONTEND='{
            "frontend":"javascript",
            "framework":"react",
            "config":{"SourceDir":"src","DistributionDir":"dist","BuildCommand":"npm run build","StartCommand":"npm start"}
          }'

          PROVIDERS='{
            "awscloudformation":{
              "configLevel":"project",
              "useProfile":false,
              "accessKeyId":"${AWS_ACCESS_KEY_ID}",
              "secretAccessKey":"${AWS_SECRET_ACCESS_KEY}",
              "region":"${{ secrets.AWS_REGION }}"
            }
          }'

          amplify pull \
            --amplify "$AMPLIFY" \
            --frontend "$FRONTEND" \
            --providers "$PROVIDERS" \
            --yes

          amplify publish --yes
